# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default
  demands:
  - agent.name -equals microserviceLearnVm1

jobs:
- job: job1
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
- job: job2
  steps:
  - script: echo Hello1, world!
    displayName: 'Run a one-line scrip1t'
  - script: echo Hello19880980, world!
    displayName: 'Run a one-line scrip1t'  

